from __future__ import annotations

type ExerciseSeed = tuple[str, str, str, str]
type TemplateExerciseSeed = tuple[str, int, str, int]
type TemplateDaySeed = tuple[str, list[TemplateExerciseSeed]]

LEGACY_TEMPLATE_SLUGS = {"upper-lower-4x"}

# Difficulty is intentionally catalog metadata rather than a property of a
# particular program. Keep the technically demanding movements explicit; the
# remaining exercises form the intermediate tier unless listed as approachable
# beginner variants below.
BEGINNER_EXERCISE_SLUGS = {
    "machine-chest-press",
    "machine-incline-chest-press",
    "independent-lever-chest-press",
    "machine-decline-chest-press",
    "smith-bench-press",
    "push-up",
    "pec-deck",
    "lat-pulldown",
    "reverse-grip-lat-pulldown",
    "close-grip-lat-pulldown",
    "straight-arm-pulldown",
    "chest-supported-row",
    "seated-cable-row",
    "machine-row",
    "lever-high-row",
    "lever-low-row",
    "independent-lever-lat-pulldown",
    "machine-pullover",
    "chest-supported-dumbbell-row",
    "inverted-row",
    "hyperextension",
    "pendulum-squat",
    "plate-loaded-leg-press",
    "machine-hip-thrust",
    "machine-glute-kickback",
    "v-squat-machine",
    "goblet-squat",
    "bodyweight-squat",
    "smith-squat",
    "belt-squat",
    "leg-press",
    "reverse-lunge",
    "step-up",
    "leg-extension",
    "wall-sit",
    "leg-curl",
    "seated-leg-curl",
    "standing-leg-curl",
    "single-leg-hip-thrust",
    "bodyweight-glute-bridge",
    "hip-abduction",
    "hip-adduction",
    "cable-kickback",
    "machine-shoulder-press",
    "independent-lever-shoulder-press",
    "smith-shoulder-press",
    "dumbbell-lateral-raise",
    "cable-lateral-raise",
    "machine-lateral-raise",
    "dumbbell-front-raise",
    "reverse-pec-deck",
    "face-pull",
    "dumbbell-shrug",
    "dumbbell-curl",
    "hammer-curl",
    "cable-curl",
    "concentration-curl",
    "machine-biceps-curl",
    "rope-pushdown",
    "cable-pushdown",
    "bench-dip",
    "triceps-kickback",
    "machine-dip",
    "machine-triceps-extension",
    "single-arm-cable-triceps-extension",
    "standing-calf-raise",
    "seated-calf-raise",
    "calf-press",
    "plank",
    "crunch",
    "reverse-crunch",
    "captain-chair-leg-raise",
    "dead-hang",
    "dead-bug",
    "bird-dog",
    "jump-rope",
    "rowing-machine",
    "treadmill-run",
    "assault-bike",
    "elliptical-trainer",
    "stationary-bike",
    "recumbent-bike",
    "outdoor-walk",
    "treadmill-walk",
    "stair-climber",
    "assisted-pull-ups",
    "assisted-dips",
    "scapular-pull-ups",
    "cable-external-rotation",
    "band-pull-apart",
    "db-squat",
    "machine-seated-crunch",
}

ADVANCED_EXERCISE_SLUGS = {
    "weighted-dip",
    "chest-dip",
    "deadlift",
    "rack-pull",
    "pull-up",
    "chin-up",
    "pendlay-row",
    "meadows-row",
    "good-morning",
    "front-squat",
    "walking-lunge",
    "bulgarian-split-squat",
    "sissy-squat",
    "single-leg-rdl",
    "nordic-curl",
    "glute-ham-raise",
    "kettlebell-swing",
    "sumo-deadlift",
    "overhead-press",
    "arnold-press",
    "landmine-press",
    "upright-row",
    "skull-crusher",
    "hanging-leg-raise",
    "ab-wheel",
    "burpee",
    "box-jump",
    "battle-rope",
    "sled-push",
    "sled-pull",
    "farmer-walk",
    "medicine-ball-slam",
    "wall-ball",
    "thruster",
    "kettlebell-clean",
    "kettlebell-snatch",
    "turkish-get-up",
    "renegade-row",
    "push-press",
    "pistol-squat",
    "overhead-squat",
    "trap-bar-deadlift",
    "safety-bar-squat",
    "negative-pull-ups",
    "muscle-ups",
    "dragon-flag",
    "l-sit",
    "clean-and-jerk",
    "hang-power-clean",
    "rope-climb",
}


def exercise_difficulty_level(slug: str) -> str:
    if slug in BEGINNER_EXERCISE_SLUGS:
        return "beginner"
    if slug in ADVANCED_EXERCISE_SLUGS:
        return "advanced"
    return "intermediate"


EXERCISE_CATALOG: list[ExerciseSeed] = [
    ("bench-press", "Жим лежа", "Грудь", "Штанга"),
    ("incline-bench-press", "Жим штанги на наклонной скамье", "Грудь", "Штанга"),
    ("decline-bench-press", "Жим штанги вниз головой", "Грудь", "Штанга"),
    ("close-grip-bench-press", "Жим лежа узким хватом", "Трицепс", "Штанга"),
    ("dumbbell-bench-press", "Жим гантелей лежа", "Грудь", "Гантели"),
    ("incline-dumbbell-press", "Жим гантелей на наклонной скамье", "Грудь", "Гантели"),
    ("decline-dumbbell-press", "Жим гантелей вниз головой", "Грудь", "Гантели"),
    ("dumbbell-fly", "Разведение гантелей лежа", "Грудь", "Гантели"),
    ("incline-dumbbell-fly", "Разведение гантелей на наклонной скамье", "Грудь", "Гантели"),
    ("cable-fly", "Сведение рук в кроссовере", "Грудь", "Кроссовер"),
    ("low-to-high-cable-fly", "Сведение снизу вверх в кроссовере", "Грудь", "Кроссовер"),
    ("pec-deck", "Сведение рук в тренажере", "Грудь", "Тренажер"),
    ("machine-chest-press", "Жим от груди в тренажере", "Грудь", "Тренажер"),
    (
        "machine-incline-chest-press",
        "Жим от груди вверх в тренажёре",
        "Грудь",
        "Тренажёр",
    ),
    (
        "independent-lever-chest-press",
        "Жим от груди в независимом рычажном тренажёре",
        "Грудь",
        "Тренажёр",
    ),
    (
        "machine-decline-chest-press",
        "Жим от груди вниз в тренажёре",
        "Грудь",
        "Тренажёр",
    ),
    ("smith-bench-press", "Жим лежа в Смите", "Грудь", "Машина Смита"),
    ("push-up", "Отжимания", "Грудь", "Собственный вес"),
    ("weighted-dip", "Отжимания на брусьях с весом", "Грудь", "Брусья"),
    ("chest-dip", "Отжимания на брусьях с наклоном", "Грудь", "Брусья"),
    ("dumbbell-pullover", "Пуловер с гантелью", "Грудь", "Гантели"),
    ("deadlift", "Становая тяга", "Спина", "Штанга"),
    ("rack-pull", "Тяга с плинтов", "Спина", "Штанга"),
    ("pull-up", "Подтягивания", "Спина", "Турник"),
    ("chin-up", "Подтягивания обратным хватом", "Спина", "Турник"),
    ("lat-pulldown", "Вертикальная тяга", "Спина", "Тренажер"),
    ("reverse-grip-lat-pulldown", "Вертикальная тяга обратным хватом", "Спина", "Тренажер"),
    ("close-grip-lat-pulldown", "Вертикальная тяга узким хватом", "Спина", "Тренажер"),
    ("straight-arm-pulldown", "Пуловер в кроссовере прямыми руками", "Спина", "Кроссовер"),
    ("barbell-row", "Тяга штанги в наклоне", "Спина", "Штанга"),
    ("pendlay-row", "Тяга Пендлея", "Спина", "Штанга"),
    ("t-bar-row", "Тяга Т-грифа", "Спина", "Тренажер"),
    ("one-arm-dumbbell-row", "Тяга гантели одной рукой", "Спина", "Гантели"),
    ("chest-supported-row", "Тяга с упором грудью", "Спина", "Тренажер"),
    ("seated-cable-row", "Горизонтальная тяга блока", "Спина", "Блок"),
    ("machine-row", "Горизонтальная тяга в тренажёре", "Спина", "Тренажёр"),
    (
        "lever-high-row",
        "Верхняя рычажная тяга с упором грудью",
        "Спина",
        "Тренажёр",
    ),
    (
        "lever-low-row",
        "Нижняя рычажная тяга с упором грудью",
        "Спина",
        "Тренажёр",
    ),
    (
        "independent-lever-lat-pulldown",
        "Вертикальная рычажная тяга независимыми руками",
        "Спина",
        "Тренажёр",
    ),
    ("machine-pullover", "Пуловер в тренажёре", "Спина", "Тренажёр"),
    (
        "chest-supported-dumbbell-row",
        "Тяга гантелей с упором грудью",
        "Спина",
        "Гантели",
    ),
    ("inverted-row", "Австралийские подтягивания", "Спина", "Собственный вес"),
    ("meadows-row", "Тяга Медоуза", "Спина", "Штанга"),
    ("cable-row-one-arm", "Тяга блока одной рукой", "Спина", "Блок"),
    ("hyperextension", "Гиперэкстензия", "Разгибатели спины", "Тренажер"),
    ("good-morning", "Наклоны со штангой", "Задняя цепь", "Штанга"),
    ("squat", "Приседания", "Квадрицепс", "Штанга"),
    ("front-squat", "Фронтальные приседания", "Квадрицепс", "Штанга"),
    ("hack-squat", "Гакк-присед", "Квадрицепс", "Тренажер"),
    ("smith-squat", "Приседания в Смите", "Квадрицепс", "Машина Смита"),
    ("goblet-squat", "Гоблет-присед с гирей", "Квадрицепс", "Гиря"),
    (
        "bodyweight-squat",
        "Приседания с собственным весом",
        "Квадрицепс",
        "Собственный вес",
    ),
    ("belt-squat", "Поясной присед", "Квадрицепс", "Тренажер"),
    ("leg-press", "Жим ногами", "Квадрицепс", "Тренажер"),
    (
        "pendulum-squat",
        "Маятниковый присед в тренажёре",
        "Квадрицепс",
        "Тренажёр",
    ),
    (
        "plate-loaded-leg-press",
        "Жим ногами в тренажёре с дисками",
        "Квадрицепс",
        "Тренажёр",
    ),
    (
        "unilateral-leg-press",
        "Жим одной ногой в тренажёре",
        "Квадрицепс",
        "Тренажёр",
    ),
    ("v-squat-machine", "V-присед в рычажном тренажёре", "Квадрицепс", "Тренажёр"),
    ("lunge", "Выпады", "Ноги", "Гантели"),
    ("walking-lunge", "Выпады в ходьбе", "Ноги", "Гантели"),
    ("reverse-lunge", "Обратные выпады", "Ноги", "Гантели"),
    ("bulgarian-split-squat", "Болгарские сплит-приседания", "Ноги", "Гантели"),
    ("split-squat", "Сплит-присед", "Ноги", "Гантели"),
    ("smith-split-squat", "Сплит-присед в машине Смита", "Ноги", "Машина Смита"),
    ("step-up", "Зашагивания на тумбу", "Ноги", "Гантели"),
    ("leg-extension", "Разгибание ног", "Квадрицепс", "Тренажер"),
    ("sissy-squat", "Сисси-присед", "Квадрицепс", "Собственный вес"),
    ("wall-sit", "Стульчик у стены", "Квадрицепс", "Собственный вес"),
    ("romanian-deadlift", "Румынская тяга", "Бицепс бедра", "Штанга"),
    ("stiff-leg-deadlift", "Тяга на прямых ногах", "Бицепс бедра", "Штанга"),
    ("single-leg-rdl", "Румынская тяга на одной ноге", "Бицепс бедра", "Гантели"),
    ("leg-curl", "Сгибание ног лежа", "Бицепс бедра", "Тренажер"),
    ("seated-leg-curl", "Сгибание ног сидя", "Бицепс бедра", "Тренажер"),
    ("standing-leg-curl", "Сгибание ноги стоя", "Бицепс бедра", "Тренажер"),
    ("nordic-curl", "Нордические сгибания", "Бицепс бедра", "Собственный вес"),
    ("glute-ham-raise", "Подъем корпуса GHD", "Бицепс бедра", "Тренажер"),
    (
        "reverse-hyperextension",
        "Обратная гиперэкстензия",
        "Задняя цепь",
        "Тренажёр",
    ),
    (
        "hip-thrust",
        "Ягодичный мост со штангой с опорой на скамью",
        "Ягодицы",
        "Штанга",
    ),
    ("single-leg-hip-thrust", "Ягодичный мост на одной ноге", "Ягодицы", "Собственный вес"),
    (
        "bodyweight-glute-bridge",
        "Ягодичный мост с собственным весом",
        "Ягодицы",
        "Собственный вес",
    ),
    ("barbell-glute-bridge", "Ягодичный мост со штангой с пола", "Ягодицы", "Штанга"),
    (
        "machine-hip-thrust",
        "Ягодичный мост в рычажном тренажёре",
        "Ягодицы",
        "Тренажёр",
    ),
    ("cable-pull-through", "Протяжка между ног в кроссовере", "Ягодицы", "Кроссовер"),
    ("kettlebell-swing", "Махи гирей", "Задняя цепь", "Гиря"),
    ("hip-abduction", "Отведение бедра в тренажере", "Ягодицы", "Тренажер"),
    ("hip-adduction", "Сведение бедер в тренажере", "Приводящие", "Тренажер"),
    ("cable-kickback", "Отведение ноги назад в кроссовере", "Ягодицы", "Кроссовер"),
    (
        "machine-glute-kickback",
        "Разгибание бедра назад в тренажёре",
        "Ягодицы",
        "Тренажёр",
    ),
    ("sumo-deadlift", "Становая тяга сумо", "Ноги", "Штанга"),
    ("overhead-press", "Жим стоя", "Плечи", "Штанга"),
    ("seated-dumbbell-press", "Жим гантелей сидя", "Плечи", "Гантели"),
    ("arnold-press", "Жим Арнольда", "Плечи", "Гантели"),
    ("machine-shoulder-press", "Жим плечами в тренажере", "Плечи", "Тренажер"),
    (
        "independent-lever-shoulder-press",
        "Жим над головой в независимом рычажном тренажёре",
        "Плечи",
        "Тренажёр",
    ),
    ("smith-shoulder-press", "Жим сидя в Смите", "Плечи", "Машина Смита"),
    ("landmine-press", "Жим штанги в упоре", "Плечи", "Штанга"),
    ("dumbbell-lateral-raise", "Подъем гантелей через стороны", "Средняя дельта", "Гантели"),
    (
        "cable-lateral-raise",
        "Подъем руки через сторону в кроссовере",
        "Средняя дельта",
        "Кроссовер",
    ),
    ("machine-lateral-raise", "Подъем через стороны в тренажере", "Средняя дельта", "Тренажер"),
    ("dumbbell-front-raise", "Подъем гантелей перед собой", "Передняя дельта", "Гантели"),
    ("rear-delt-fly", "Разведение гантелей в наклоне", "Задняя дельта", "Гантели"),
    ("reverse-pec-deck", "Обратная бабочка", "Задняя дельта", "Тренажер"),
    ("face-pull", "Тяга каната к лицу", "Задняя дельта", "Кроссовер"),
    ("upright-row", "Тяга к подбородку", "Плечи", "Штанга"),
    ("barbell-shrug", "Шраги со штангой", "Трапеции", "Штанга"),
    ("dumbbell-shrug", "Шраги с гантелями", "Трапеции", "Гантели"),
    ("y-raise", "Y-подъемы", "Нижняя трапеция", "Гантели"),
    ("barbell-curl", "Подъем штанги на бицепс", "Бицепс", "Штанга"),
    ("ez-bar-curl", "Подъем EZ-штанги на бицепс", "Бицепс", "EZ-штанга"),
    ("dumbbell-curl", "Подъем гантелей на бицепс", "Бицепс", "Гантели"),
    ("hammer-curl", "Молотковые сгибания", "Бицепс", "Гантели"),
    ("incline-dumbbell-curl", "Сгибания гантелей на наклонной скамье", "Бицепс", "Гантели"),
    ("preacher-curl", "Сгибания на скамье Скотта", "Бицепс", "Скамья Скотта"),
    ("cable-curl", "Сгибания рук в кроссовере", "Бицепс", "Кроссовер"),
    ("concentration-curl", "Концентрированные сгибания", "Бицепс", "Гантели"),
    ("reverse-curl", "Подъем штанги обратным хватом", "Предплечья", "Штанга"),
    ("barbell-wrist-curl", "Сгибание кистей со штангой", "Предплечья", "Штанга"),
    (
        "barbell-wrist-extension",
        "Разгибание кистей со штангой",
        "Предплечья",
        "Штанга",
    ),
    ("spider-curl", "Паучьи сгибания", "Бицепс", "Скамья"),
    ("machine-biceps-curl", "Сгибание рук в тренажере", "Бицепс", "Тренажер"),
    ("skull-crusher", "Французский жим лежа", "Трицепс", "EZ-штанга"),
    ("rope-pushdown", "Разгибание рук с канатом", "Трицепс", "Кроссовер"),
    ("cable-pushdown", "Разгибание рук на блоке", "Трицепс", "Блок"),
    (
        "overhead-triceps-extension",
        "Разгибание рук из-за головы в кроссовере",
        "Трицепс",
        "Кроссовер",
    ),
    ("dumbbell-overhead-extension", "Французский жим гантели сидя", "Трицепс", "Гантель"),
    ("lying-dumbbell-triceps-extension", "Разгибание гантелей лежа", "Трицепс", "Гантели"),
    ("bench-dip", "Обратные отжимания от скамьи", "Трицепс", "Собственный вес"),
    ("triceps-kickback", "Разгибание руки назад с гантелью", "Трицепс", "Гантель"),
    ("machine-dip", "Отжимания в тренажере", "Трицепс", "Тренажер"),
    ("machine-triceps-extension", "Разгибание рук в тренажёре", "Трицепс", "Тренажёр"),
    ("single-arm-cable-triceps-extension", "Разгибание одной руки на блоке", "Трицепс", "Блок"),
    ("standing-calf-raise", "Подъемы на носки стоя", "Икры", "Тренажер"),
    ("seated-calf-raise", "Подъемы на носки сидя", "Икры", "Тренажер"),
    ("donkey-calf-raise", "Ослиные подъемы на носки", "Икры", "Тренажер"),
    ("calf-press", "Жим носками в тренажере", "Икры", "Тренажер"),
    ("single-leg-calf-raise", "Подъем на носок одной ногой", "Икры", "Собственный вес"),
    ("plank", "Планка", "Кор", "Собственный вес"),
    ("side-plank", "Боковая планка", "Кор", "Собственный вес"),
    ("crunch", "Скручивания", "Пресс", "Собственный вес"),
    ("reverse-crunch", "Обратные скручивания", "Пресс", "Собственный вес"),
    ("cable-crunch", "Скручивания на блоке", "Пресс", "Блок"),
    ("hanging-leg-raise", "Подъем ног в висе", "Пресс", "Турник"),
    ("dead-hang", "Вис на перекладине", "Хват", "Турник"),
    ("captain-chair-leg-raise", "Подъем ног в упоре", "Пресс", "Тренажер"),
    ("ab-wheel", "Ролик для пресса", "Кор", "Ролик"),
    ("russian-twist", "Русские повороты", "Косые мышцы", "Медбол"),
    ("pallof-press", "Жим Палофа", "Кор", "Кроссовер"),
    ("woodchopper", "Дровосек в кроссовере", "Косые мышцы", "Кроссовер"),
    ("mountain-climber", "Альпинист", "Кор", "Собственный вес"),
    ("hollow-hold", "Холлоу-холд", "Кор", "Собственный вес"),
    ("dead-bug", "Мертвый жук", "Кор", "Собственный вес"),
    ("bird-dog", "Берд-дог", "Кор", "Собственный вес"),
    ("burpee", "Берпи", "Все тело", "Собственный вес"),
    ("box-jump", "Запрыгивания на тумбу", "Ноги", "Тумба"),
    ("jump-rope", "Скакалка", "Кардио", "Скакалка"),
    ("rowing-machine", "Гребля на кардиотренажёре", "Кардио", "Гребной тренажёр"),
    ("treadmill-run", "Беговая дорожка", "Кардио", "Беговая дорожка"),
    ("assault-bike", "Воздушный велотренажёр", "Кардио", "Воздушный велотренажёр"),
    ("outdoor-run", "Бег на улице", "Кардио", "Без оборудования"),
    ("elliptical-trainer", "Эллиптический тренажёр", "Кардио", "Эллиптический тренажёр"),
    ("outdoor-cycling", "Велосипед", "Кардио", "Велосипед"),
    ("stationary-bike", "Велотренажёр", "Кардио", "Велотренажёр"),
    (
        "recumbent-bike",
        "Горизонтальный велотренажёр",
        "Кардио",
        "Горизонтальный велотренажёр",
    ),
    ("outdoor-walk", "Ходьба", "Кардио", "Без оборудования"),
    ("treadmill-walk", "Ходьба на дорожке", "Кардио", "Беговая дорожка"),
    ("stair-climber", "Степпер / лестница", "Кардио", "Степпер"),
    ("swimming", "Плавание", "Кардио", "Бассейн"),
    ("ski-erg", "Лыжный тренажёр", "Кардио", "Лыжный эргометр"),
    ("battle-rope", "Канаты", "Кондиция", "Канаты"),
    ("sled-push", "Толкание саней", "Ноги", "Сани"),
    ("sled-pull", "Тяга саней", "Задняя цепь", "Сани"),
    ("farmer-walk", "Прогулка фермера", "Хват", "Гантели"),
    ("suitcase-carry", "Чемоданная переноска", "Кор", "Гиря"),
    ("medicine-ball-slam", "Броски медбола в пол", "Все тело", "Медбол"),
    ("wall-ball", "Броски мяча в стену", "Все тело", "Медбол"),
    ("thruster", "Трастер", "Все тело", "Штанга"),
    ("kettlebell-clean", "Взятие гири на грудь", "Все тело", "Гиря"),
    ("kettlebell-snatch", "Рывок гири", "Все тело", "Гиря"),
    ("kettlebell-goblet-squat", "Гоблет-присед с гирей", "Ноги", "Гиря"),
    ("turkish-get-up", "Турецкий подъем", "Все тело", "Гиря"),
    ("renegade-row", "Ренегатская тяга", "Спина", "Гантели"),
    ("bear-crawl", "Медвежья проходка", "Все тело", "Собственный вес"),
    ("floor-press", "Жим с пола", "Грудь", "Штанга"),
    ("push-press", "Пуш-пресс", "Плечи", "Штанга"),
    ("assisted-pull-ups", "Подтягивания с противовесом", "Спина", "Тренажёр"),
    ("decline-crunch", "Скручивания на наклонной скамье", "Пресс", "Скамья"),
    ("pistol-squat", "Приседания на одной ноге", "Квадрицепс", "Собственный вес"),
    ("overhead-squat", "Приседания со штангой над головой", "Квадрицепс", "Штанга"),
    ("cable-external-rotation", "Внешняя ротация плеча в кроссовере", "Плечи", "Кроссовер"),
    ("hanging-knee-raise", "Подъём коленей в висе", "Пресс", "Турник"),
    ("trap-bar-deadlift", "Тяга с трэп-грифом", "Задняя цепь", "Штанга"),
    ("safety-bar-squat", "Приседания с safety bar", "Квадрицепс", "Штанга"),
    ("negative-pull-ups", "Негативные подтягивания", "Спина", "Турник"),
    ("scapular-pull-ups", "Лопаточные подтягивания", "Спина", "Турник"),
    ("muscle-ups", "Выходы силой", "Спина", "Турник"),
    ("assisted-dips", "Отжимания на брусьях с противовесом", "Трицепс", "Тренажёр"),
    ("machine-seated-crunch", "Скручивания в тренажёре сидя", "Пресс", "Тренажёр"),
    ("band-pull-apart", "Разведения резинки перед собой", "Задняя дельта", "Другое"),
    ("db-squat", "Приседания с гантелями", "Квадрицепс", "Гантели"),
    ("kettlebell-overhead-carry", "Переноска гири над головой", "Хват", "Гиря"),
    ("dragon-flag", "Драконий флаг", "Кор", "Собственный вес"),
    ("jackknife-sit-up", "Складка лёжа", "Пресс", "Собственный вес"),
    ("l-sit", "L-сит", "Кор", "Брусья"),
    ("clean-and-jerk", "Взятие штанги на грудь и толчок", "Все тело", "Штанга"),
    ("hang-power-clean", "Взятие штанги на грудь с виса", "Все тело", "Штанга"),
    ("wrist-roller", "Ролик для предплечий", "Предплечья", "Ролик"),
    ("rope-climb", "Лазание по канату", "Спина", "Канаты"),
]

PPLF_4_DAYS: list[TemplateDaySeed] = [
    (
        "Тяни",
        [
            ("pull-up", 4, "6-10", 120),
            ("barbell-row", 4, "6-8", 150),
            ("lat-pulldown", 3, "10-12", 90),
            ("barbell-curl", 3, "8-10", 90),
        ],
    ),
    (
        "Толкай",
        [
            ("bench-press", 4, "5-8", 150),
            ("incline-dumbbell-press", 3, "8-10", 120),
            ("overhead-press", 3, "6-8", 150),
            ("rope-pushdown", 3, "10-12", 75),
        ],
    ),
    (
        "Ноги",
        [
            ("squat", 4, "5-8", 180),
            ("leg-press", 3, "10-12", 150),
            ("romanian-deadlift", 3, "8-10", 150),
            ("standing-calf-raise", 4, "12-15", 60),
        ],
    ),
    (
        "Фуллбади",
        [
            ("front-squat", 3, "6-8", 150),
            ("dumbbell-bench-press", 3, "8-10", 120),
            ("seated-cable-row", 3, "10-12", 90),
            ("hip-thrust", 3, "8-10", 120),
        ],
    ),
]

PPLF_8_DAYS: list[TemplateDaySeed] = [
    *PPLF_4_DAYS,
    (
        "Тяни B",
        [
            ("deadlift", 3, "3-5", 180),
            ("chest-supported-row", 4, "8-10", 120),
            ("close-grip-lat-pulldown", 3, "10-12", 90),
            ("hammer-curl", 3, "10-12", 75),
        ],
    ),
    (
        "Толкай B",
        [
            ("incline-bench-press", 4, "6-8", 150),
            ("machine-chest-press", 3, "10-12", 90),
            ("seated-dumbbell-press", 3, "8-10", 120),
            ("overhead-triceps-extension", 3, "10-12", 75),
        ],
    ),
    (
        "Ноги B",
        [
            ("front-squat", 4, "6-8", 150),
            ("bulgarian-split-squat", 3, "8-10", 120),
            ("hip-thrust", 4, "8-10", 120),
            ("seated-calf-raise", 4, "12-15", 60),
        ],
    ),
    (
        "Фуллбади B",
        [
            ("goblet-squat", 3, "10-12", 90),
            ("machine-chest-press", 3, "10-12", 90),
            ("machine-row", 3, "10-12", 90),
            ("plank", 3, "30-60 сек", 60),
        ],
    ),
]

PLPL_4_DAYS: list[TemplateDaySeed] = [
    (
        "Тяни",
        [
            ("pull-up", 4, "6-10", 120),
            ("barbell-row", 4, "6-8", 150),
            ("lat-pulldown", 3, "10-12", 90),
            ("barbell-curl", 3, "8-10", 90),
        ],
    ),
    (
        "Ноги A · акцент на квадрицепс",
        [
            ("squat", 4, "5-8", 180),
            ("leg-press", 3, "10-12", 150),
            ("leg-extension", 3, "12-15", 75),
            ("standing-calf-raise", 4, "12-15", 60),
        ],
    ),
    (
        "Толкай",
        [
            ("bench-press", 4, "5-8", 150),
            ("incline-dumbbell-press", 3, "8-10", 120),
            ("overhead-press", 3, "6-8", 150),
            ("rope-pushdown", 3, "10-12", 75),
        ],
    ),
    (
        "Ноги B · акцент на заднюю цепь",
        [
            ("romanian-deadlift", 4, "6-8", 180),
            ("hip-thrust", 4, "8-10", 120),
            ("seated-leg-curl", 3, "10-12", 90),
            ("seated-calf-raise", 4, "12-15", 60),
        ],
    ),
]

PLPL_8_DAYS: list[TemplateDaySeed] = [
    *PLPL_4_DAYS,
    (
        "Тяни B",
        [
            ("deadlift", 3, "3-5", 180),
            ("chest-supported-row", 4, "8-10", 120),
            ("close-grip-lat-pulldown", 3, "10-12", 90),
            ("hammer-curl", 3, "10-12", 75),
        ],
    ),
    (
        "Ноги C · односторонняя работа",
        [
            ("front-squat", 4, "6-8", 150),
            ("bulgarian-split-squat", 3, "8-10", 120),
            ("step-up", 3, "10-12", 90),
            ("single-leg-calf-raise", 3, "12-15", 60),
        ],
    ),
    (
        "Толкай B",
        [
            ("incline-bench-press", 4, "6-8", 150),
            ("machine-chest-press", 3, "10-12", 90),
            ("seated-dumbbell-press", 3, "8-10", 120),
            ("overhead-triceps-extension", 3, "10-12", 75),
        ],
    ),
    (
        "Ноги D · ягодицы и бицепс бедра",
        [
            ("sumo-deadlift", 4, "5-8", 180),
            ("single-leg-rdl", 3, "8-10", 120),
            ("single-leg-hip-thrust", 3, "10-12", 90),
            ("leg-curl", 3, "10-12", 90),
        ],
    ),
]

STRENGTH_TEMPLATE_SPECS: list[dict[str, object]] = [
    {
        "slug": "strength-pplf-4d",
        "title": "Тяни/Толкай/Ноги/Фуллбади · 4 дня",
        "goal": "recomposition",
        "level": "intermediate",
        "split_type": "hybrid",
        "days": PPLF_4_DAYS,
    },
    {
        "slug": "strength-pplf-8d",
        "title": "Тяни/Толкай/Ноги/Фуллбади · 8 дней",
        "goal": "muscle_gain",
        "level": "advanced",
        "split_type": "hybrid",
        "days": PPLF_8_DAYS,
    },
    {
        "slug": "strength-pull-legs-push-legs-4d",
        "title": "Тяни/Ноги/Толкай/Ноги · 4 дня",
        "goal": "recomposition",
        "level": "intermediate",
        "split_type": "hybrid",
        "days": PLPL_4_DAYS,
    },
    {
        "slug": "strength-pull-legs-push-legs-8d",
        "title": "Тяни/Ноги/Толкай/Ноги · 8 дней",
        "goal": "muscle_gain",
        "level": "advanced",
        "split_type": "hybrid",
        "days": PLPL_8_DAYS,
    },
    {
        "slug": "strength-split-5d",
        "title": "Силовой сплит 5 дней",
        "goal": "muscle_gain",
        "level": "intermediate",
        "split_type": "body_part",
        "days": [
            (
                "Грудь",
                [
                    ("bench-press", 4, "6-8", 150),
                    ("incline-dumbbell-press", 4, "8-10", 120),
                    ("machine-chest-press", 3, "10-12", 90),
                    ("cable-fly", 3, "12-15", 75),
                    ("weighted-dip", 3, "8-10", 120),
                ],
            ),
            (
                "Спина",
                [
                    ("pull-up", 4, "6-10", 120),
                    ("barbell-row", 4, "6-8", 150),
                    ("seated-cable-row", 3, "10-12", 90),
                    ("lat-pulldown", 3, "10-12", 90),
                    ("straight-arm-pulldown", 3, "12-15", 75),
                ],
            ),
            (
                "Ноги",
                [
                    ("squat", 4, "5-8", 180),
                    ("leg-press", 4, "10-12", 150),
                    ("romanian-deadlift", 3, "8-10", 150),
                    ("leg-curl", 3, "10-12", 90),
                    ("standing-calf-raise", 4, "12-15", 60),
                ],
            ),
            (
                "Плечи",
                [
                    ("overhead-press", 4, "6-8", 150),
                    ("dumbbell-lateral-raise", 4, "12-15", 60),
                    ("reverse-pec-deck", 3, "12-15", 75),
                    ("face-pull", 3, "12-15", 75),
                    ("dumbbell-shrug", 3, "10-12", 90),
                ],
            ),
            (
                "Руки",
                [
                    ("close-grip-bench-press", 4, "6-8", 150),
                    ("barbell-curl", 4, "8-10", 90),
                    ("rope-pushdown", 3, "10-12", 75),
                    ("hammer-curl", 3, "10-12", 75),
                    ("overhead-triceps-extension", 3, "12-15", 75),
                ],
            ),
        ],
    },
    {
        "slug": "strength-push-pull-legs-6d",
        "title": "Тяни-толкай-ноги 6 дней",
        "goal": "muscle_gain",
        "level": "advanced",
        "split_type": "push_pull_legs",
        "days": [
            (
                "Толкай A",
                [
                    ("bench-press", 4, "5-8", 150),
                    ("incline-dumbbell-press", 3, "8-10", 120),
                    ("overhead-press", 3, "6-8", 150),
                    ("dumbbell-lateral-raise", 3, "12-15", 60),
                    ("rope-pushdown", 3, "10-12", 75),
                ],
            ),
            (
                "Тяни A",
                [
                    ("pull-up", 4, "6-10", 120),
                    ("barbell-row", 4, "6-8", 150),
                    ("lat-pulldown", 3, "10-12", 90),
                    ("face-pull", 3, "12-15", 75),
                    ("barbell-curl", 3, "8-10", 90),
                ],
            ),
            (
                "Ноги A",
                [
                    ("squat", 4, "5-8", 180),
                    ("leg-press", 3, "10-12", 150),
                    ("romanian-deadlift", 3, "8-10", 150),
                    ("leg-curl", 3, "10-12", 90),
                    ("standing-calf-raise", 4, "12-15", 60),
                ],
            ),
            (
                "Толкай B",
                [
                    ("incline-bench-press", 4, "6-8", 150),
                    ("machine-chest-press", 3, "10-12", 90),
                    ("seated-dumbbell-press", 3, "8-10", 120),
                    ("cable-lateral-raise", 3, "12-15", 60),
                    ("overhead-triceps-extension", 3, "10-12", 75),
                ],
            ),
            (
                "Тяни B",
                [
                    ("deadlift", 3, "3-5", 180),
                    ("chest-supported-row", 4, "8-10", 120),
                    ("close-grip-lat-pulldown", 3, "10-12", 90),
                    ("rear-delt-fly", 3, "12-15", 75),
                    ("hammer-curl", 3, "10-12", 75),
                ],
            ),
            (
                "Ноги B",
                [
                    ("front-squat", 4, "6-8", 150),
                    ("bulgarian-split-squat", 3, "8-10", 120),
                    ("hip-thrust", 4, "8-10", 120),
                    ("leg-extension", 3, "12-15", 75),
                    ("seated-calf-raise", 4, "12-15", 60),
                ],
            ),
        ],
    },
    {
        "slug": "strength-upper-lower-4d",
        "title": "Верх-низ 4 дня",
        "goal": "recomposition",
        "level": "intermediate",
        "split_type": "upper_lower",
        "days": [
            (
                "Верх A",
                [
                    ("bench-press", 4, "5-8", 150),
                    ("barbell-row", 4, "6-8", 150),
                    ("overhead-press", 3, "6-8", 120),
                    ("lat-pulldown", 3, "10-12", 90),
                    ("rope-pushdown", 3, "10-12", 75),
                    ("barbell-curl", 3, "10-12", 75),
                ],
            ),
            (
                "Низ A",
                [
                    ("squat", 4, "5-8", 180),
                    ("romanian-deadlift", 4, "8-10", 150),
                    ("leg-press", 3, "10-12", 120),
                    ("leg-curl", 3, "10-12", 90),
                    ("standing-calf-raise", 4, "12-15", 60),
                ],
            ),
            (
                "Верх B",
                [
                    ("incline-dumbbell-press", 4, "8-10", 120),
                    ("pull-up", 4, "6-10", 120),
                    ("seated-dumbbell-press", 3, "8-10", 120),
                    ("seated-cable-row", 3, "10-12", 90),
                    ("dumbbell-lateral-raise", 3, "12-15", 60),
                    ("face-pull", 3, "12-15", 60),
                ],
            ),
            (
                "Низ B",
                [
                    ("front-squat", 4, "6-8", 150),
                    ("hip-thrust", 4, "8-10", 120),
                    ("bulgarian-split-squat", 3, "8-10", 120),
                    ("seated-leg-curl", 3, "10-12", 90),
                    ("seated-calf-raise", 4, "12-15", 60),
                ],
            ),
        ],
    },
    {
        "slug": "strength-fullbody-3d",
        "title": "Фуллбади 3 дня",
        "goal": "recomposition",
        "level": "beginner",
        "split_type": "full_body",
        "days": [
            (
                "Фуллбади A",
                [
                    ("squat", 4, "6-8", 150),
                    ("bench-press", 4, "6-8", 150),
                    ("seated-cable-row", 3, "10-12", 90),
                    ("romanian-deadlift", 3, "8-10", 120),
                    ("plank", 3, "30-60 сек", 60),
                ],
            ),
            (
                "Фуллбади B",
                [
                    ("deadlift", 3, "3-5", 180),
                    ("overhead-press", 4, "6-8", 150),
                    ("lat-pulldown", 3, "10-12", 90),
                    ("leg-press", 3, "10-12", 120),
                    ("hanging-leg-raise", 3, "10-15", 60),
                ],
            ),
            (
                "Фуллбади C",
                [
                    ("front-squat", 4, "6-8", 150),
                    ("incline-dumbbell-press", 3, "8-10", 120),
                    ("barbell-row", 4, "6-8", 150),
                    ("hip-thrust", 3, "8-10", 120),
                    ("face-pull", 3, "12-15", 60),
                ],
            ),
        ],
    },
]
