name = "yfc-allure-report-origin"
main = "src/index.js"
compatibility_date = "2026-09-07"
workers_dev = false

[[r2_buckets]]
binding = "REPORTS"
bucket_name = "yfc-allure-reports"

[[routes]]
pattern = "allure.your-fitness-coach.ru"
custom_domain = true
